function [autocorrelation] = autocorrelation(delay)
%AUTOCORRELATION Summary of this function goes here
%   Detailed explanation goes here

signal = reference_signal(configuration.satellite, ...
                0, ...
                configuration.chippingFrequency, ...
                configuration.sampplingFrequency, ...
                1)';
signalDelayed = reference_signal(configuration.satellite, ...
                delay, ...
                configuration.chippingFrequency, ...
                configuration.sampplingFrequency, ...
                1)';
autocorrelation = signal * signalDelayed;
end

