function [autocorrelation] = autocorrelation(delay, configuration)
%AUTOCORRELATION Summary of this function goes here
%   Detailed explanation goes here

signal = reference_signal(configuration.satellite, ...
                0, ...
                configuration.chippingFrequency, ...
                configuration.samplingFrequency, ...
                1)';
autocorrelation = zeros(size(delay, 1), size(delay, 2));
for i = 1:size(delay, 1)
    for j = 1:size(delay, 2)
    signalDelayed = reference_signal(configuration.satellite, ...
                    delay(i, j), ...
                    configuration.chippingFrequency, ...
                    configuration.samplingFrequency, ...
                    1)';
    autocorrelation(i, j) = signal' * signalDelayed;
    end
end
end

