function result = runDissertationEkf( ...
    trial, parameters, delayProcessNoiseVariance, ...
    tapProcessNoiseVariance)
%RUNDISSERTATIONEKF Run the fixed-Jacobian causal EKF dissertation model.

configuration = trial.configuration;
channelProcessCovariance = ...
    tapProcessNoiseVariance * eye(parameters.tapCount);
Q = blkdiag(delayProcessNoiseVariance, channelProcessCovariance);

initialDelayEstimate = trial.trueDelayEpochRecord(1) + ...
    parameters.initialDelayErrorSamples / configuration.samplingFrequency;
initialChannelCovarianceMatrix = ...
    parameters.initialChannelStd^2 * eye(parameters.tapCount);

x_k_k_1 = zeros(parameters.stateDimension, 1);
x_k_k_1(parameters.delayStateIndex) = initialDelayEstimate;
x_k_k_1(parameters.mainTapStateIndex) = 1;

P_k_k_1 = blkdiag(parameters.initialDelayStd^2, ...
    initialChannelCovarianceMatrix);

correlatorBank = buildCorrelatorBank( ...
    configuration, x_k_k_1(parameters.delayStateIndex), parameters.q);
carrierToNoiseRatioLinear = ...
    10^(configuration.carrierToNoiseDensityRatio / 10);
thermalNoiseVariance = ...
    configuration.samplingFrequency / carrierToNoiseRatioLinear;
R = (thermalNoiseVariance / parameters.samplesTotal) * ...
    ((correlatorBank * correlatorBank') / parameters.samplesTotal);

delayEstimateRecord = zeros(1, parameters.simulationSteps);
channelStateRecord = zeros(parameters.tapCount, parameters.simulationSteps);
innovationRecord = zeros(parameters.C, parameters.simulationSteps);
posteriorCovarianceRecord = zeros( ...
    parameters.stateDimension, parameters.stateDimension, ...
    parameters.simulationSteps);

for k = 1:parameters.simulationSteps
    receivedSignal = trial.simulatedSignal( ...
        ((k - 1) * parameters.samplesTotal + 1: ...
        k * parameters.samplesTotal));

    if k > 1
        correlatorBank = buildCorrelatorBank( ...
            configuration, x_k_k_1(parameters.delayStateIndex), ...
            parameters.q);

        z_k = (correlatorBank * receivedSignal) / ...
            parameters.samplesTotal;
        channelWeights = x_k_k_1(parameters.tapStateIndices);
        currentShiftedCorrelations = getShiftedCorrelationsFromBank( ...
            correlatorBank, ...
            x_k_k_1(parameters.delayStateIndex), ...
            configuration, ...
            parameters.channelTapDelays);
        channelWeightsJacobian = currentShiftedCorrelations / ...
            parameters.samplesTotal;
        z_hat_k_aux = channelWeightsJacobian * channelWeights;
        z_hat_k = z_hat_k_aux;

        delayJacobian = delayJacobianFunctionSimplified( ...
            0, ...
            channelWeights, ...
            1 / configuration.samplingFrequency, ...
            parameters.q, ...
            1 / configuration.chippingFrequency, ...
            1, ...
            0);

        jacobian = [delayJacobian channelWeightsJacobian];

        PJacobianTranspose = P_k_k_1 * jacobian';
        innovationCovariance = jacobian * PJacobianTranspose + R;
        K_k = PJacobianTranspose * ...
            (innovationCovariance \ eye(parameters.C));

        innovation = z_k - z_hat_k;
        innovationRecord(:, k) = innovation;

        x_k_k = x_k_k_1 + K_k * innovation;
        x_k_k(parameters.delayStateIndex) = ...
            real(x_k_k(parameters.delayStateIndex));

        P_k_k = ...
            (eye(parameters.stateDimension) - K_k * jacobian) * P_k_k_1;
    else
        x_k_k = x_k_k_1;
        P_k_k = P_k_k_1;
    end

    posteriorCovarianceRecord(:, :, k) = P_k_k;

    x_k_k_1 = x_k_k;
    x_k_k_1(parameters.delayStateIndex) = ...
        real(x_k_k_1(parameters.delayStateIndex));
    P_k_k_1 = P_k_k + Q;

    delayEstimateRecord(:, k) = x_k_k(parameters.delayStateIndex);
    channelStateRecord(:, k) = x_k_k(parameters.tapStateIndices);
end

metricSamples = parameters.metricStartIndex:parameters.simulationSteps;

result.delayEstimateRecord = delayEstimateRecord;
result.trueDelayRecord = trial.trueDelayRecord;
result.channelStateRecord = channelStateRecord;
result.truthChannelState = trial.truthChannelState;
result.innovationRecord = innovationRecord;
result.posteriorCovarianceRecord = posteriorCovarianceRecord;
result.timeMs = parameters.timeMs;
result.delayMape = meanAbsolutePercentageError( ...
    trial.trueDelayRecord(metricSamples), delayEstimateRecord(metricSamples));
result.channelMape = meanAbsolutePercentageError( ...
    repmat(trial.truthChannelState, 1, numel(metricSamples)), ...
    channelStateRecord(:, metricSamples));

end
